name: CD

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0

      - name: npm ci, build
        run: |
          npm ci
          npm run build --if-present

      - name: Pushes to ttc-eta
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "build"
          destination-github-username: "thomassth"
          destination-repository-name: "ttc-eta"
          user-email: "41898282+github-actions[bot]@users.noreply.github.com"
          user-name: "github-actions[bot]"
          target-branch: main
